name: Sync develop after merge to main

on:
  push:
    branches:
      - main

jobs:
  sync-develop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # importante para ter todo o histórico

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Fetch all branches
        run: git fetch origin

      - name: Checkout develop branch
        run: |
          git checkout develop
          git pull origin develop
          git merge origin/main || echo "Nothing to merge"

      - name: Push develop
        run: git push origin develop
